name: ai4physicshydrology
channels:
        - conda-forge
dependencies:
        - torchdiffeq
        - pytest
        - black
        - tqdm
        - matplotlib
        - xarray
        - netCDF4
        - pip
